[package]
name = "adventofcode"
version = "0.1.0"
authors = ["ia0 <git@ia0.eu>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
data-encoding = "2.3.3"
internment = "0.7.0"
md-5 = "0.10.5"
number-encoding = "0.2.1"
regex = "1.7.0"
