[package]
name = "adventofcode"
version = "0.1.0"
authors = ["ia0 <git@ia0.eu>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
data-encoding = "2.3.2"
lazy_static = "1.4.0"
number-encoding = "0.2.1"
regex = "1.7.0"
